In [6]:
from sql_rag_ollama import SQLRAG
import pandas as pd
import time

In [2]:
model = SQLRAG()

In [5]:
df = pd.read_csv("data/eval_cases.csv", sep=",")
times = []
for question in df["Question"]:
    start_time = time.perf_counter()
    print("Question:", question)
    model.prompt(question, print_results=True)
    print()
    end_time = time.perf_counter()
    times.append(end_time - start_time)

print(times)

Question: What prevalence of diabetes was recorded in germany in 2015 for males in the age group 18+?
|    |   value |
|---:|--------:|
|  0 |  8.1332 |

In 2015, Germany recorded an age-standardized prevalence of diabetes at 8.1332% among males aged 18 years and older.

Question: What prevalence of diabetes was recorded in germany in 2015 for males in the age group 30+?
|    |   value |
|---:|--------:|
|  0 | 11.0239 |

In 2015, Germany recorded an age-standardized prevalence rate of diabetes for males aged 30 years and above at approximately 11.02%. This statistic reflects the percentage of individuals within this demographic who were diagnosed with diabetes in that year.

Question: What prevalence of diabetes was recorded in germany in 2015 for females in the age group 18+?
|    |   value |
|---:|--------:|
|  0 | 5.18364 |

In Germany, for females aged 18 years and older, the prevalence of diabetes in 2015 was recorded at approximately 5.18%. This figure represents the age-standardized rate for that demographic group during the specified year.

Question: What prevalence of diabetes was recorded in germany in 2015 for females in the age group 30+?
|    |   value |
|---:|--------:|
|  0 | 6.93159 |

In 2015, Germany recorded a prevalence rate of approximately 6.93% for diabetes among females aged 30 years and older. This figure represents the age-standardized percentage of diabetic cases within this demographic.

Question: What prevalence of diabetes was recorded in germany in 2015 for the age group 18+?
|    |   value |
|---:|--------:|
|  0 | 6.6232  |
|  1 | 8.1332  |
|  2 | 5.18364 |

In 2015, the age-standardized prevalence of diabetes for individuals aged 18 and older in Germany was reported with three different values: 6.6232%, 8.1332%, and 5.18364%. These figures suggest variability depending on different data sources or methodologies used to estimate the prevalence within that year.

Question: What prevalence of diabetes was recorded in 2015 for the age group 18+?
|     | country                                                  |   year | sex        | agegroup         |    value |
|----:|:---------------------------------------------------------|-------:|:-----------|:-----------------|---------:|
|   0 | denmark                                                  |   2015 | female     | 18+ years of age |  1.92205 |
|   1 | tuvalu                                                   |   2015 | male       | 18+ years of age | 13.3047  |
|   2 | madagascar                                               |   2015 | female     | 18+ years of age |  8.03813 |
|   3 | kiribati                                                 |   2015 | both sexes | 18+ years of age | 22.284   |
|   4 | panama                                                   |   2015 | female     | 18+ years of age |  9.23514 |
|   5 | bulgaria                                                 |   2015 | male       | 18+ years of age |  9.63999 |
|   6 | paraguay                                                 |   2015 | female     | 18+ years of age | 12.4018  |
|   7 | brazil                                                   |   2015 | male       | 18+ years of age |  9.54306 |
|   8 | montenegro                                               |   2015 | both sexes | 18+ years of age |  8.57296 |
|   9 | greece                                                   |   2015 | female     | 18+ years of age |  5.94126 |
|  10 | united republic of tanzania                              |   2015 | both sexes | 18+ years of age |  6.72165 |
|  11 | american samoa                                           |   2015 | female     | 18+ years of age | 30.8937  |
|  12 | egypt                                                    |   2015 | female     | 18+ years of age | 23.9167  |
|  13 | mauritania                                               |   2015 | both sexes | 18+ years of age |  9.26257 |
|  14 | philippines                                              |   2015 | both sexes | 18+ years of age |  8.72228 |
|  15 | guyana                                                   |   2015 | male       | 18+ years of age | 16.0823  |
|  16 | lebanon                                                  |   2015 | both sexes | 18+ years of age | 17.4479  |
|  17 | american samoa                                           |   2015 | male       | 18+ years of age | 33.1409  |
|  18 | sao tome and principe                                    |   2015 | both sexes | 18+ years of age | 12.2718  |
|  19 | portugal                                                 |   2015 | male       | 18+ years of age |  8.47052 |
|  20 | bangladesh                                               |   2015 | female     | 18+ years of age | 17.7547  |
|  21 | cook islands                                             |   2015 | both sexes | 18+ years of age | 29.4334  |
|  22 | morocco                                                  |   2015 | male       | 18+ years of age | 15.7104  |
|  23 | maldives                                                 |   2015 | male       | 18+ years of age |  8.98941 |
|  24 | lesotho                                                  |   2015 | both sexes | 18+ years of age |  6.68989 |
|  25 | mongolia                                                 |   2015 | both sexes | 18+ years of age | 10.7937  |
|  26 | tuvalu                                                   |   2015 | both sexes | 18+ years of age | 15.1888  |
|  27 | jordan                                                   |   2015 | both sexes | 18+ years of age | 19.4172  |
|  28 | t√ºrkiye                                                  |   2015 | both sexes | 18+ years of age | 14.0642  |
|  29 | gambia                                                   |   2015 | both sexes | 18+ years of age | 10.6169  |
|  30 | cambodia                                                 |   2015 | female     | 18+ years of age |  7.34175 |
|  31 | marshall islands                                         |   2015 | both sexes | 18+ years of age | 32.6785  |
|  32 | montenegro                                               |   2015 | male       | 18+ years of age |  9.75846 |
|  33 | cuba                                                     |   2015 | both sexes | 18+ years of age | 11.556   |
|  34 | uzbekistan                                               |   2015 | both sexes | 18+ years of age | 12.8414  |
|  35 | togo                                                     |   2015 | female     | 18+ years of age |  7.68783 |
|  36 | liberia                                                  |   2015 | male       | 18+ years of age | 10.7312  |
|  37 | tonga                                                    |   2015 | male       | 18+ years of age | 19.475   |
|  38 | belarus                                                  |   2015 | male       | 18+ years of age |  6.09844 |
|  39 | uruguay                                                  |   2015 | female     | 18+ years of age | 11.9152  |
|  40 | angola                                                   |   2015 | both sexes | 18+ years of age | 16.1716  |
|  41 | indonesia                                                |   2015 | male       | 18+ years of age |  7.62153 |
|  42 | new zealand                                              |   2015 | both sexes | 18+ years of age |  7.51408 |
|  43 | iran (islamic republic of)                               |   2015 | male       | 18+ years of age | 12.2355  |
|  44 | republic of korea                                        |   2015 | male       | 18+ years of age | 10.6971  |
|  45 | netherlands (kingdom of the)                             |   2015 | both sexes | 18+ years of age |  5.56847 |
|  46 | central african republic                                 |   2015 | female     | 18+ years of age | 17.8167  |
|  47 | croatia                                                  |   2015 | both sexes | 18+ years of age |  7.54398 |
|  48 | saint vincent and the grenadines                         |   2015 | both sexes | 18+ years of age | 12.9383  |
|  49 | tajikistan                                               |   2015 | both sexes | 18+ years of age | 12.0518  |
|  50 | brunei darussalam                                        |   2015 | male       | 18+ years of age | 15.2671  |
|  51 | japan                                                    |   2015 | male       | 18+ years of age |  7.41576 |
|  52 | vanuatu                                                  |   2015 | female     | 18+ years of age | 18.1938  |
|  53 | syrian arab republic                                     |   2015 | male       | 18+ years of age | 20.8514  |
|  54 | jamaica                                                  |   2015 | female     | 18+ years of age | 23.3     |
|  55 | venezuela (bolivarian republic of)                       |   2015 | female     | 18+ years of age | 10.4693  |
|  56 | colombia                                                 |   2015 | male       | 18+ years of age | 10.9647  |
|  57 | south sudan                                              |   2015 | both sexes | 18+ years of age |  7.67749 |
|  58 | poland                                                   |   2015 | male       | 18+ years of age |  9.18725 |
|  59 | democratic people's republic of korea                    |   2015 | female     | 18+ years of age | 10.3809  |
|  60 | senegal                                                  |   2015 | male       | 18+ years of age |  7.6121  |
|  61 | equatorial guinea                                        |   2015 | male       | 18+ years of age | 11.5942  |
|  62 | serbia                                                   |   2015 | male       | 18+ years of age |  9.67053 |
|  63 | sudan                                                    |   2015 | male       | 18+ years of age | 10.6424  |
|  64 | bangladesh                                               |   2015 | male       | 18+ years of age | 14.5577  |
|  65 | seychelles                                               |   2015 | both sexes | 18+ years of age | 16.569   |
|  66 | yemen                                                    |   2015 | male       | 18+ years of age | 15.0966  |
|  67 | nauru                                                    |   2015 | male       | 18+ years of age | 25.5767  |
|  68 | tokelau                                                  |   2015 | male       | 18+ years of age | 34.2499  |
|  69 | greece                                                   |   2015 | male       | 18+ years of age |  8.46929 |
|  70 | costa rica                                               |   2015 | male       | 18+ years of age | 17.7293  |
|  71 | cook islands                                             |   2015 | female     | 18+ years of age | 30.2256  |
|  72 | burundi                                                  |   2015 | male       | 18+ years of age |  7.29246 |
|  73 | uzbekistan                                               |   2015 | male       | 18+ years of age | 11.847   |
|  74 | cabo verde                                               |   2015 | male       | 18+ years of age |  9.04963 |
|  75 | turkmenistan                                             |   2015 | both sexes | 18+ years of age | 16.8641  |
|  76 | turkmenistan                                             |   2015 | female     | 18+ years of age | 18.2207  |
|  77 | cyprus                                                   |   2015 | both sexes | 18+ years of age |  7.17308 |
|  78 | maldives                                                 |   2015 | both sexes | 18+ years of age | 10.2049  |
|  79 | mozambique                                               |   2015 | both sexes | 18+ years of age |  6.84405 |
|  80 | sao tome and principe                                    |   2015 | male       | 18+ years of age | 12.0236  |
|  81 | occupied palestinian territory, including east jerusalem |   2015 | female     | 18+ years of age | 20.6711  |
|  82 | germany                                                  |   2015 | both sexes | 18+ years of age |  6.6232  |
|  83 | mozambique                                               |   2015 | male       | 18+ years of age |  7.54872 |
|  84 | cook islands                                             |   2015 | male       | 18+ years of age | 28.5897  |
|  85 | ghana                                                    |   2015 | both sexes | 18+ years of age |  7.55368 |
|  86 | spain                                                    |   2015 | male       | 18+ years of age |  6.41986 |
|  87 | guinea                                                   |   2015 | female     | 18+ years of age |  8.93357 |
|  88 | tunisia                                                  |   2015 | both sexes | 18+ years of age | 13.8462  |
|  89 | yemen                                                    |   2015 | both sexes | 18+ years of age | 15.8323  |
|  90 | sierra leone                                             |   2015 | female     | 18+ years of age |  9.78208 |
|  91 | el salvador                                              |   2015 | male       | 18+ years of age | 10.9782  |
|  92 | democratic republic of the congo                         |   2015 | female     | 18+ years of age |  8.93888 |
|  93 | qatar                                                    |   2015 | female     | 18+ years of age | 24.4885  |
|  94 | somalia                                                  |   2015 | female     | 18+ years of age |  8.69503 |
|  95 | united kingdom of great britain and northern ireland     |   2015 | female     | 18+ years of age |  6.03504 |
|  96 | czechia                                                  |   2015 | female     | 18+ years of age |  5.62618 |
|  97 | antigua and barbuda                                      |   2015 | both sexes | 18+ years of age | 18.0181  |
|  98 | central african republic                                 |   2015 | both sexes | 18+ years of age | 17.4662  |
|  99 | portugal                                                 |   2015 | both sexes | 18+ years of age |  6.65637 |
| 100 | lesotho                                                  |   2015 | male       | 18+ years of age |  5.25832 |
| 101 | timor-leste                                              |   2015 | female     | 18+ years of age |  5.67115 |
| 102 | kuwait                                                   |   2015 | female     | 18+ years of age | 23.769   |
| 103 | republic of korea                                        |   2015 | female     | 18+ years of age |  7.48941 |
| 104 | nicaragua                                                |   2015 | both sexes | 18+ years of age | 13.3718  |
| 105 | viet nam                                                 |   2015 | both sexes | 18+ years of age |  6.798   |
| 106 | uganda                                                   |   2015 | male       | 18+ years of age |  4.28265 |
| 107 | argentina                                                |   2015 | female     | 18+ years of age |  9.32422 |
| 108 | israel                                                   |   2015 | both sexes | 18+ years of age |  8.56875 |
| 109 | canada                                                   |   2015 | male       | 18+ years of age |  7.6141  |
| 110 | georgia                                                  |   2015 | male       | 18+ years of age |  9.82697 |
| 111 | mexico                                                   |   2015 | female     | 18+ years of age | 19.0775  |
| 112 | saint lucia                                              |   2015 | both sexes | 18+ years of age | 16.9618  |
| 113 | guinea-bissau                                            |   2015 | male       | 18+ years of age |  8.74625 |
| 114 | tuvalu                                                   |   2015 | female     | 18+ years of age | 16.9614  |
| 115 | paraguay                                                 |   2015 | male       | 18+ years of age | 11.6602  |
| 116 | iceland                                                  |   2015 | male       | 18+ years of age |  5.9533  |
| 117 | sierra leone                                             |   2015 | both sexes | 18+ years of age |  9.3245  |
| 118 | finland                                                  |   2015 | both sexes | 18+ years of age |  6.05683 |
| 119 | burundi                                                  |   2015 | both sexes | 18+ years of age |  7.67159 |
| 120 | t√ºrkiye                                                  |   2015 | female     | 18+ years of age | 14.3575  |
| 121 | nicaragua                                                |   2015 | female     | 18+ years of age | 14.1147  |
| 122 | sri lanka                                                |   2015 | both sexes | 18+ years of age | 17.922   |
| 123 | solomon islands                                          |   2015 | female     | 18+ years of age |  7.83562 |
| 124 | austria                                                  |   2015 | male       | 18+ years of age |  5.72362 |
| 125 | barbados                                                 |   2015 | male       | 18+ years of age | 17.7771  |
| 126 | united arab emirates                                     |   2015 | male       | 18+ years of age | 26.9606  |
| 127 | venezuela (bolivarian republic of)                       |   2015 | male       | 18+ years of age | 12.3581  |
| 128 | malawi                                                   |   2015 | male       | 18+ years of age |  5.20197 |
| 129 | israel                                                   |   2015 | male       | 18+ years of age |  9.83583 |
| 130 | andorra                                                  |   2015 | male       | 18+ years of age |  8.71064 |
| 131 | jamaica                                                  |   2015 | both sexes | 18+ years of age | 20.0209  |
| 132 | marshall islands                                         |   2015 | female     | 18+ years of age | 34.5397  |
| 133 | iraq                                                     |   2015 | both sexes | 18+ years of age | 22.2872  |
| 134 | zambia                                                   |   2015 | female     | 18+ years of age |  9.57947 |
| 135 | democratic people's republic of korea                    |   2015 | male       | 18+ years of age |  9.19882 |
| 136 | qatar                                                    |   2015 | both sexes | 18+ years of age | 24.5082  |
| 137 | eritrea                                                  |   2015 | both sexes | 18+ years of age |  7.30137 |
| 138 | bahamas                                                  |   2015 | both sexes | 18+ years of age | 17.1503  |
| 139 | armenia                                                  |   2015 | male       | 18+ years of age | 11.0762  |
| 140 | senegal                                                  |   2015 | both sexes | 18+ years of age |  7.98207 |
| 141 | brunei darussalam                                        |   2015 | female     | 18+ years of age | 16.2795  |
| 142 | hungary                                                  |   2015 | male       | 18+ years of age | 10.9613  |
| 143 | bolivia (plurinational state of)                         |   2015 | female     | 18+ years of age | 11.2743  |
| 144 | solomon islands                                          |   2015 | both sexes | 18+ years of age |  7.41126 |
| 145 | bulgaria                                                 |   2015 | both sexes | 18+ years of age |  8.55339 |
| 146 | honduras                                                 |   2015 | male       | 18+ years of age | 10.7775  |
| 147 | guinea-bissau                                            |   2015 | female     | 18+ years of age |  9.7859  |
| 148 | dominica                                                 |   2015 | female     | 18+ years of age | 27.235   |

In [32]:
import requests
import json

values = []
i = 0
site = "indicatordefinitions"
while True:
    data = requests.get(f"https://www.who.int/api/news/{site}?$skip={i}").json()
    print(i)
    if not data['value']: break
    values += data['value']
    i+=50

with open("data/" + site + ".json", "w") as f:
    json.dump(values, f)

0
50
100
150
200
250
300
350
400
450
500
550
600
650
700
750
800
850
900
950
1000
1050
1100
1150
1200
1250
1300
1350
1400
1450
1500
1550
1600
1650
1700
1750
1800
1850
1900
1950
2000
2050
2100
2150
2200
2250
2300

In [ ]:
with open("data/indicatordefinitions.json", "r") as f:
    defs = json.load(f)

with open("data/indicatormetadataregistrydefinitions.json", "r") as f:
    metadata = json.load(f)

result = [(i,ind) for i, ind in enumerate(defs) if ind["Code"] is not None and "NCD_DIABETES_PREVALENCE_AGESTD" in ind["Code"]]
#id = result[0]["Id"]

[md for md in metadata if md["Id"] == id]
#metadata
(result[0][0] // 50) * 50

2200